# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fossee/testarea/gui/ldmicro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fossee/testarea/gui/ldmicro

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fossee/testarea/gui/ldmicro/CMakeFiles /home/fossee/testarea/gui/ldmicro/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fossee/testarea/gui/ldmicro/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LDMicro

# Build rule for target.
LDMicro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LDMicro
.PHONY : LDMicro

# fast build rule for target.
LDMicro/fast:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/build
.PHONY : LDMicro/fast

draw_outputdev.o: draw_outputdev.cpp.o
.PHONY : draw_outputdev.o

# target to build an object file
draw_outputdev.cpp.o:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/draw_outputdev.cpp.o
.PHONY : draw_outputdev.cpp.o

draw_outputdev.i: draw_outputdev.cpp.i
.PHONY : draw_outputdev.i

# target to preprocess a source file
draw_outputdev.cpp.i:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/draw_outputdev.cpp.i
.PHONY : draw_outputdev.cpp.i

draw_outputdev.s: draw_outputdev.cpp.s
.PHONY : draw_outputdev.s

# target to generate assembly for a file
draw_outputdev.cpp.s:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/draw_outputdev.cpp.s
.PHONY : draw_outputdev.cpp.s

ldmicro.o: ldmicro.cpp.o
.PHONY : ldmicro.o

# target to build an object file
ldmicro.cpp.o:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/ldmicro.cpp.o
.PHONY : ldmicro.cpp.o

ldmicro.i: ldmicro.cpp.i
.PHONY : ldmicro.i

# target to preprocess a source file
ldmicro.cpp.i:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/ldmicro.cpp.i
.PHONY : ldmicro.cpp.i

ldmicro.s: ldmicro.cpp.s
.PHONY : ldmicro.s

# target to generate assembly for a file
ldmicro.cpp.s:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/ldmicro.cpp.s
.PHONY : ldmicro.cpp.s

miscutil.o: miscutil.cpp.o
.PHONY : miscutil.o

# target to build an object file
miscutil.cpp.o:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/miscutil.cpp.o
.PHONY : miscutil.cpp.o

miscutil.i: miscutil.cpp.i
.PHONY : miscutil.i

# target to preprocess a source file
miscutil.cpp.i:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/miscutil.cpp.i
.PHONY : miscutil.cpp.i

miscutil.s: miscutil.cpp.s
.PHONY : miscutil.s

# target to generate assembly for a file
miscutil.cpp.s:
	$(MAKE) -f CMakeFiles/LDMicro.dir/build.make CMakeFiles/LDMicro.dir/miscutil.cpp.s
.PHONY : miscutil.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... LDMicro"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... draw_outputdev.o"
	@echo "... draw_outputdev.i"
	@echo "... draw_outputdev.s"
	@echo "... ldmicro.o"
	@echo "... ldmicro.i"
	@echo "... ldmicro.s"
	@echo "... miscutil.o"
	@echo "... miscutil.i"
	@echo "... miscutil.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

